-- Data Definition Lang
CREATE TABLE Users (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(20) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Firstname VARCHAR(255) NOT NULL,
    Lastname VARCHAR(255) NOT NULL DEFAULT '-',
    Email VARCHAR(200) NOT NULL UNIQUE,
    RememberToken VARCHAR(255) DEFAULT NULL
);